### ISSUE TITLE
 State value has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by neorulez** [StrathCole/ioBroker.plenticore#41] opened 2021-05-06 20:55 UTC
There are several warnings in the log after update to latest js-controller
For example: 

plenticore.0 | 2021-05-06 22:49:54.090 | info | (8881) State value to set for "plenticore.0.forecast.current.power.max" has to be type "number" but received type "string"
-- | -- | -- | --
plenticore.0 | 2021-05-06 22:49:54.089 | info | (8881) State value to set for "plenticore.0.forecast.current.sun.azimuth" has to be type "number" but received type "string"
plenticore.0 | 2021-05-06 22:49:54.088 | info | (8881) State value to set for "plenticore.0.forecast.current.sun.elevation" has to be type "number" but received type "string"

Adapter version is 2.1.9
Node.js is v12.22.1

**Comment by StrathCole** [comment] 2021-05-07 08:02
This is a duplicate of #37

**Closed by StrathCole** 2021-05-07 08:02 UTC
